services:
  db:
    image: mariadb:10.6
    container_name: prestashop_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashoppass
    volumes:
      - db_data:/var/lib/mysql

  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop_app
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      DB_SERVER: $(DB_SERVER)
      DB_NAME: $(DB_NAME)
      DB_USER: $(DB_USER)
      DB_PASSWD: $(DB_PASSWD)
      PS_INSTALL_AUTO: 1
      PS_DEV_MODE: 1
      PS_DOMAIN: localhost:8080
    volumes:
      - prestashop_data:/var/www/html
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: prestashop_phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: $(PMA_HOST)
      PMA_USER: root
      PMA_PASSWORD: $(PMA_PASSWORD)
    restart: always

volumes:
  db_data:
  prestashop_data: