services:
  db:
    image: mariadb:10.6
    container_name: prestashop_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $(MYSQL_ROOT_PASSWORD)
      MYSQL_DATABASE: $(MYSQL_DATABASE)
      MYSQL_USER: $(MYSQL_USER)
      MYSQL_PASSWORD: $(MYSQL_PASSWORD)
    volumes:
      - db_data:/var/lib/mysql

  prestashop:
    image: prestashop/prestashop
    container_name: prestashop_app
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      DB_SERVER: $(DB_SERVER)
      DB_NAME: $(DB_NAME)
      DB_USER: $(DB_USER)
      DB_PASSWORD: $(DB_PASSWD)
      DB_HOST: $(DB_HOST)
    volumes:
      - prestashop_data:/var/www/html
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: prestashop_phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: $(PMA_HOST)
      PMA_USER: root
      PMA_PASSWORD: $(PMA_PASSWORD)
    restart: always

volumes:
  db_data:
  prestashop_data: